### ISSUE TITLE
Publish the zip content as release and put the content of the zip in the repo

### ISSUE THREAD

**Issue by gbraad** [UUoocl/Obsidian_AdvancedSlides_Demo_Vault#1]
This is a self-contained setup, but this makes it hard to intregate this into an existing setup.

Consider publishing the zip content in the repo and use a release to zip this up.

**Comment by gbraad** [comment]
I published an example of this at: https://github.com/gbraad/AdvancedSlides-to-OBS

**Comment by UUoocl** [comment]
Thank you for your interest in this project and for creating the unzipped example!  I'm working on instructions and an updated script. Both should be post this week.

**Comment by gbraad** [comment]
Looking forward.Closing the issue for now.
